version: "3.9"
services:
  app:
    container_name: react-sample
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - type: bind
      source: ./app
      target: /home/takane/Documents/react-sample/app
    #"react-sample"の部分がプロジェクト名になる
    command: sh -c "cd react-sample && npm install && yarn start" 
    ports:
      - 3000:3000
    stdin_open: true #標準入力をコンテナと紐付ける